### ISSUE TITLE
EEA countries

### ISSUE THREAD

**Issue by asgjon** [staaky/vatrates#5]
Iceland, Liechtenstein and Norway are all part of The European Economic Area and should therefore be regarded as VAT countries. isVATCountry returns false for all three. Is it possible to add those and historical values for them as well?

**Comment by staaky** [comment]
The countries in the json file are those where [EU VAT](https://en.wikipedia.org/wiki/European_Union_value_added_tax) applies. The countries you mentioned are not included because the rules when applying VAT seem to be different for countries outside the EU.

https://ec.europa.eu/taxation_customs/business/vat/telecommunications-broadcasting-electronic-services_en

Documentation I've come across on EU VAT never mentions the extra 3 EEA countries. When it comes to applying EU VAT they distinguish between inside and outside EU.

So if `isVATCountry` included all EEA countries, it would no longer reliably tell you if you should be applying EU VAT. Other libraries like [jsonvat.com](http://jsonvat.com) probably don't include them for this same reason.

But perhaps we're doing it wrong, I should probably ask an accountant about this.
